apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      nodeSelector:
        type: {{ .Values.nodeSelector.type }}

      initContainers:
        - name: db-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              export DATABASE_URL="postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

              echo "Waiting for PostgreSQL..."

              until python -c "
              import psycopg2
              psycopg2.connect(
                  host='${DB_HOST}',
                  port=${DB_PORT},
                  dbname='${DB_NAME}',
                  user='${DB_USERNAME}',
                  password='${DB_PASSWORD}'
              )
              "; do
                echo "PostgreSQL is not ready yet..."
                sleep 2
              done

              echo "PostgreSQL is ready."
              flask db upgrade

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config

            - secretRef:
                name: {{ .Values.secret.name }}

      containers:
        - name: student-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              export DATABASE_URL="postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
              exec gunicorn --bind 0.0.0.0:5000 run:app

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config

            - secretRef:
                name: {{ .Values.secret.name }}
