apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}

spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.secretStore.vault.server | quote }}
      path: {{ .Values.externalSecrets.secretStore.vault.path | quote }}
      version: {{ .Values.externalSecrets.secretStore.vault.version | quote }}

      auth:
        tokenSecretRef:
          name: {{ .Values.externalSecrets.secretStore.vault.tokenSecretName }}
          key: {{ .Values.externalSecrets.secretStore.vault.tokenSecretKey }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.externalSecret.name }}

spec:
  refreshInterval: {{ .Values.externalSecrets.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore

  target:
    name: {{ .Values.externalSecrets.externalSecret.name }}
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.externalSecret.vaultKey }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.externalSecret.vaultKey }}
        property: password
