apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-api
  namespace: observability
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - student-api

  selector:
    matchLabels:
      app: student-api

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
