apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: student-api

spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"

      auth:
        tokenSecretRef:
          name: vault-token
          key: token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-db-secret
  namespace: student-api

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore

  target:
    name: student-api-db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: student-api
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: student-api
        property: password
