apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      nodeSelector:
        type: database

      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: studentdb

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: student-api

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP

  type: ClusterIP
