name: Student REST API CI

"on":
  push:
    branches:
      - master
    paths:
      - "app/**"
      - "tests/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "requirements.txt"
      - "Makefile"
      - ".flake8"
      - ".github/workflows/ci.yml"

  workflow_dispatch:

jobs:
  ci:
    name: Build, Test, Lint and Push
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build API
        run: make build

      - name: Run tests
        run: make test

      - name: Perform code linting
        run: make lint

      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: make docker-login

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make docker-push
